#![forbid(unsafe_code)]
#![allow(clippy::missing_errors_doc)]
//! Bunting's thin, version-pinned adapter around `OrderBook-rs`.
//!
//! Matching, price levels, order types, trade generation, snapshots, replay helpers,
//! depth analytics, risk hooks, self-trade prevention, fees and the operational kill
//! switch are upstream responsibilities. Bunting owns authentication, canonical event
//! envelopes, participant accounting, persistence and Worker protocols.

use bunting_market_events::{
    AdvancedOrderPolicy, PegReference, Side as BuntingSide, TimeInForcePolicy,
};
use bunting_market_types::{OrderId, PriceTicks, QuantityLots};
use orderbook_rs::orderbook::OrderBookSnapshotPackage;
use orderbook_rs::orderbook::modifications::OrderQuantity;
use orderbook_rs::{DefaultOrderBook, Id, OrderBookError, Side, TradeResult};
use pricelevel::{Hash32, OrderType, PegReferenceType, Price, Quantity};
use std::num::NonZeroU64;
use std::str::FromStr;
use std::sync::Arc;

use orderbook_rs::StubClock;
pub(crate) use orderbook_rs::{TimeInForce, TradeInfo};

/// Released upstream version approved for the Bunting kernel.
pub const ORDERBOOK_RS_VERSION: &str = "0.10.3";
/// Audited upstream source revision corresponding to the adopted implementation pass.
pub const ORDERBOOK_RS_AUDIT_COMMIT: &str = "575de34260b0fce346372074b6b938df058693a8";

/// Visible `(price, quantity)` pairs for one snapshot side.
pub type VisibleLevels = Vec<(u128, u64)>;

/// Decodes validated visible levels from an upstream snapshot package.
///
/// # Errors
/// Returns [`OrderBookError`] when JSON decoding, version, or checksum validation fails.
pub fn visible_levels_from_snapshot_json(
    json: &str,
) -> Result<(VisibleLevels, VisibleLevels), OrderBookError> {
    let package = OrderBookSnapshotPackage::from_json(json)?;
    package.validate()?;
    let levels = |items: &[pricelevel::PriceLevelSnapshot]| {
        items
            .iter()
            .map(|level| (level.price().as_u128(), level.visible_quantity().as_u64()))
            .collect()
    };
    Ok((
        levels(&package.snapshot.bids),
        levels(&package.snapshot.asks),
    ))
}

/// Result of one limit-order submission through the upstream engine.
#[derive(Debug)]
pub struct LimitSubmission {
    /// Fills generated by this submission, when it crossed resting liquidity.
    pub trade_result: Option<TradeResult>,
}

/// Exact persisted snapshot package metadata.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SnapshotPackage {
    /// Serialized upstream package.
    pub json: String,
    /// Upstream SHA-256 checksum.
    pub checksum: String,
    /// Upstream engine sequence represented.
    pub engine_sequence: u64,
}

/// Checked protocol-to-upstream conversion failure.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ConversionError {
    /// The external order identifier exceeds the sequential upstream range.
    OrderIdOutOfRange,
    /// Prices must be positive and representable as `u128`.
    InvalidPrice,
    /// Quantities must be positive and representable as `u64`.
    InvalidQuantity,
}

/// Converts a Bunting order identifier into the supported upstream range.
pub fn to_upstream_order_id(order_id: OrderId) -> Result<u64, ConversionError> {
    u64::try_from(order_id.get()).map_err(|_| ConversionError::OrderIdOutOfRange)
}

/// Converts a positive fixed-point price into upstream ticks.
pub fn to_upstream_price(price: PriceTicks) -> Result<u128, ConversionError> {
    u128::try_from(price.get())
        .ok()
        .filter(|value| *value > 0)
        .ok_or(ConversionError::InvalidPrice)
}

/// Converts a positive fixed-point quantity into upstream lots.
pub fn to_upstream_quantity(quantity: QuantityLots) -> Result<u64, ConversionError> {
    u64::try_from(quantity.get())
        .ok()
        .filter(|value| *value > 0)
        .ok_or(ConversionError::InvalidQuantity)
}

/// Converts Bunting side identity without changing semantics.
#[must_use]
pub const fn to_upstream_side(side: BuntingSide) -> Side {
    match side {
        BuntingSide::Buy => Side::Buy,
        BuntingSide::Sell => Side::Sell,
    }
}

/// Maps the durable protocol policy to the released matcher policy.
#[must_use]
pub const fn to_upstream_time_in_force(policy: TimeInForcePolicy) -> TimeInForce {
    match policy {
        TimeInForcePolicy::Gtc => TimeInForce::Gtc,
        TimeInForcePolicy::Ioc => TimeInForce::Ioc,
        TimeInForcePolicy::Fok => TimeInForce::Fok,
        TimeInForcePolicy::Gtd { expires_at_millis } => TimeInForce::Gtd(expires_at_millis),
        TimeInForcePolicy::Day => TimeInForce::Day,
    }
}

/// Recovers a sequential upstream identifier from its stable textual form.
#[must_use]
pub fn sequential_id_from_text(value: &str) -> Option<u64> {
    Id::from_str(value).ok().and_then(|id| id.as_u64())
}

/// The production book wrapper used by Bunting.
///
/// This type intentionally does not expose a second Bunting-owned matching structure.
pub struct KernelBook {
    inner: DefaultOrderBook,
}

impl KernelBook {
    /// Creates a book backed by `OrderBook-rs`.
    #[must_use]
    pub fn new(symbol: &str) -> Self {
        Self::new_at(symbol, 0)
    }

    /// Creates a deterministic book using a recorded logical millisecond.
    #[must_use]
    pub fn new_at(symbol: &str, logical_millis: u64) -> Self {
        Self {
            inner: DefaultOrderBook::with_clock(
                symbol,
                Arc::new(StubClock::starting_at(logical_millis)),
            ),
        }
    }

    /// Exposes the upstream API for capabilities Bunting has not wrapped yet.
    #[must_use]
    #[cfg(test)]
    pub const fn inner(&self) -> &DefaultOrderBook {
        &self.inner
    }

    /// Submits a limit order and returns only fills attributable to this call.
    pub fn submit_limit(
        &self,
        order_id: u64,
        price: u128,
        quantity: u64,
        side: Side,
        time_in_force: TimeInForce,
    ) -> Result<LimitSubmission, OrderBookError> {
        let (order, trade_result) = self.inner.add_limit_order_with_result(
            Id::sequential(order_id),
            price,
            quantity,
            side,
            time_in_force,
            None,
        )?;

        let _order_id = order.id().to_string();
        Ok(LimitSubmission { trade_result })
    }

    /// Submits a released OrderBook-rs special order without exposing the matcher.
    #[expect(
        clippy::too_many_lines,
        reason = "one exhaustive construction maps each approved upstream special-order variant"
    )]
    pub fn submit_advanced_limit(
        &self,
        order_id: u64,
        price: u128,
        quantity: u64,
        side: Side,
        time_in_force: TimeInForcePolicy,
        policy: AdvancedOrderPolicy,
    ) -> Result<LimitSubmission, OrderBookError> {
        let id = Id::sequential(order_id);
        let price = Price::new(price);
        let quantity = Quantity::new(quantity);
        let user_id = Hash32([0; 32]);
        let timestamp = self.inner.clock().now_millis();
        let time_in_force = to_upstream_time_in_force(time_in_force);
        let order = match policy {
            AdvancedOrderPolicy::PostOnly => OrderType::PostOnly {
                id,
                price,
                quantity,
                side,
                user_id,
                timestamp,
                time_in_force,
                extra_fields: (),
            },
            AdvancedOrderPolicy::Iceberg { visible_quantity } => {
                let visible = to_upstream_quantity(visible_quantity).map_err(|_| {
                    OrderBookError::InvalidLotSize {
                        quantity: 0,
                        lot_size: 1,
                    }
                })?;
                let hidden = quantity.as_u64().checked_sub(visible).ok_or(
                    OrderBookError::InvalidLotSize {
                        quantity: visible,
                        lot_size: quantity.as_u64(),
                    },
                )?;
                OrderType::IcebergOrder {
                    id,
                    price,
                    visible_quantity: Quantity::new(visible),
                    hidden_quantity: Quantity::new(hidden),
                    side,
                    user_id,
                    timestamp,
                    time_in_force,
                    extra_fields: (),
                }
            }
            AdvancedOrderPolicy::Reserve {
                visible_quantity,
                replenish_threshold,
                replenish_quantity,
                auto_replenish,
            } => {
                let visible = to_upstream_quantity(visible_quantity).map_err(|_| {
                    OrderBookError::InvalidLotSize {
                        quantity: 0,
                        lot_size: 1,
                    }
                })?;
                let hidden = quantity.as_u64().checked_sub(visible).ok_or(
                    OrderBookError::InvalidLotSize {
                        quantity: visible,
                        lot_size: quantity.as_u64(),
                    },
                )?;
                let threshold = to_upstream_quantity(replenish_threshold).map_err(|_| {
                    OrderBookError::InvalidLotSize {
                        quantity: 0,
                        lot_size: 1,
                    }
                })?;
                let replenish = to_upstream_quantity(replenish_quantity)
                    .ok()
                    .and_then(NonZeroU64::new)
                    .ok_or(OrderBookError::InvalidLotSize {
                        quantity: 0,
                        lot_size: 1,
                    })?;
                OrderType::ReserveOrder {
                    id,
                    price,
                    visible_quantity: Quantity::new(visible),
                    hidden_quantity: Quantity::new(hidden),
                    side,
                    user_id,
                    timestamp,
                    time_in_force,
                    replenish_threshold: Quantity::new(threshold),
                    replenish_amount: Some(replenish),
                    auto_replenish,
                    extra_fields: (),
                }
            }
            AdvancedOrderPolicy::Pegged {
                offset_ticks,
                reference,
            } => OrderType::PeggedOrder {
                id,
                price,
                quantity,
                side,
                user_id,
                timestamp,
                time_in_force,
                reference_price_offset: offset_ticks,
                reference_price_type: match reference {
                    PegReference::BestBid => PegReferenceType::BestBid,
                    PegReference::BestAsk => PegReferenceType::BestAsk,
                    PegReference::MidPrice => PegReferenceType::MidPrice,
                    PegReference::LastTrade => PegReferenceType::LastTrade,
                },
                extra_fields: (),
            },
            AdvancedOrderPolicy::TrailingStop { trail_ticks } => OrderType::TrailingStop {
                id,
                price,
                quantity,
                side,
                user_id,
                timestamp,
                time_in_force,
                trail_amount: Quantity::new(to_upstream_quantity(trail_ticks).map_err(|_| {
                    OrderBookError::InvalidLotSize {
                        quantity: 0,
                        lot_size: 1,
                    }
                })?),
                last_reference_price: price,
                extra_fields: (),
            },
            AdvancedOrderPolicy::MarketToLimit => OrderType::MarketToLimit {
                id,
                price,
                quantity,
                side,
                user_id,
                timestamp,
                time_in_force,
                extra_fields: (),
            },
        };
        let (_, trade_result) = self.inner.add_order_with_result(order)?;
        Ok(LimitSubmission { trade_result })
    }

    /// Submits a market order and normalizes the upstream match result into a trade result.
    pub fn submit_market(
        &self,
        order_id: u64,
        quantity: u64,
        side: Side,
    ) -> Result<TradeResult, OrderBookError> {
        let match_result =
            self.inner
                .submit_market_order(Id::sequential(order_id), quantity, side)?;
        Ok(TradeResult::new(
            self.inner.symbol().to_string(),
            match_result,
        ))
    }

    /// Returns whether the side can currently reach at least one opposite order.
    #[must_use]
    pub fn has_opposite_liquidity(&self, side: BuntingSide) -> bool {
        match side {
            BuntingSide::Buy => self.inner.best_ask().is_some(),
            BuntingSide::Sell => self.inner.best_bid().is_some(),
        }
    }

    /// Cancels an order through the upstream order-location index.
    #[cfg(test)]
    pub fn cancel(&self, order_id: u64) -> Result<bool, OrderBookError> {
        Ok(self.inner.cancel_order(Id::sequential(order_id))?.is_some())
    }

    /// Cancels an order and returns its exact remaining quantity.
    pub fn cancel_remaining(&self, order_id: u64) -> Result<Option<u64>, OrderBookError> {
        Ok(self
            .inner
            .cancel_order(Id::sequential(order_id))?
            .map(|order| order.quantity()))
    }

    /// Engages the upstream operational kill switch.
    pub fn engage_kill_switch(&self) {
        self.inner.engage_kill_switch();
    }

    /// Creates the checksum-protected upstream snapshot package as JSON.
    #[cfg(test)]
    pub fn snapshot_json(&self, depth: usize) -> Result<String, OrderBookError> {
        self.inner.create_snapshot_package(depth)?.to_json()
    }

    /// Creates a checksum-protected package with explicit metadata.
    pub fn snapshot_package(&self, depth: usize) -> Result<SnapshotPackage, OrderBookError> {
        let package = canonical_snapshot_package(self.inner.create_snapshot_package(depth)?)?;
        Ok(SnapshotPackage {
            json: package.to_json()?,
            checksum: package.checksum.clone(),
            engine_sequence: package.engine_seq,
        })
    }

    /// Restores a fresh upstream book from a validated snapshot package.
    #[cfg(test)]
    pub fn restore_snapshot_json(symbol: &str, json: &str) -> Result<Self, OrderBookError> {
        Self::restore_snapshot_json_at(symbol, json, 0)
    }

    /// Restores a package with a recorded logical clock for future operations.
    pub fn restore_snapshot_json_at(
        symbol: &str,
        json: &str,
        logical_millis: u64,
    ) -> Result<Self, OrderBookError> {
        let package = OrderBookSnapshotPackage::from_json(json)?;
        package.validate()?;
        let mut inner =
            DefaultOrderBook::with_clock(symbol, Arc::new(StubClock::starting_at(logical_millis)));
        inner.restore_from_snapshot_package(package)?;
        Ok(Self { inner })
    }
}

/// `PriceLevel` 0.8.4 initializes `first_arrival_time` from wall-clock time even
/// when OrderBook-rs uses a deterministic clock. Bunting treats these level
/// statistics as derived diagnostics, so snapshots pin that field to the
/// deterministic snapshot timestamp before recomputing the upstream checksum.
fn canonical_snapshot_package(
    package: OrderBookSnapshotPackage,
) -> Result<OrderBookSnapshotPackage, OrderBookError> {
    let mut snapshot_value = serde_json::to_value(&package.snapshot).map_err(|error| {
        OrderBookError::SerializationError {
            message: error.to_string(),
        }
    })?;
    for side in ["bids", "asks"] {
        if let Some(levels) = snapshot_value
            .get_mut(side)
            .and_then(serde_json::Value::as_array_mut)
        {
            for level in levels {
                if let Some(statistics) = level.get_mut("statistics")
                    && let Some(object) = statistics.as_object_mut()
                {
                    object.insert(
                        "first_arrival_time".to_owned(),
                        serde_json::Value::from(package.snapshot.timestamp),
                    );
                }
            }
        }
    }
    let snapshot = serde_json::from_value(snapshot_value).map_err(|error| {
        OrderBookError::DeserializationError {
            message: error.to_string(),
        }
    })?;
    let mut canonical = OrderBookSnapshotPackage::new(snapshot)?;
    canonical.fee_schedule = package.fee_schedule;
    canonical.stp_mode = package.stp_mode;
    canonical.tick_size = package.tick_size;
    canonical.lot_size = package.lot_size;
    canonical.min_order_size = package.min_order_size;
    canonical.max_order_size = package.max_order_size;
    canonical.engine_seq = package.engine_seq;
    canonical.kill_switch_engaged = package.kill_switch_engaged;
    canonical.risk_config = package.risk_config;
    canonical.market_close_timestamp = package.market_close_timestamp;
    canonical.has_market_close = package.has_market_close;
    Ok(canonical)
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use super::*;

    #[test]
    fn limit_market_and_snapshot_restore_use_upstream_engine() {
        let book = KernelBook::new("BNT/USD");
        book.submit_limit(1, 100, 10, Side::Buy, TimeInForce::Gtc)
            .unwrap();
        book.submit_limit(2, 102, 8, Side::Sell, TimeInForce::Gtc)
            .unwrap();

        let before = book.snapshot_json(10).unwrap();
        let restored = KernelBook::restore_snapshot_json("BNT/USD", &before).unwrap();
        assert_eq!(book.inner().best_bid(), restored.inner().best_bid());
        assert_eq!(book.inner().best_ask(), restored.inner().best_ask());

        let result = book.submit_market(3, 3, Side::Buy).unwrap();
        assert_eq!(
            result
                .match_result
                .executed_quantity()
                .map_or(0, pricelevel::Quantity::as_u64),
            3
        );
    }

    #[test]
    fn level_statistics_are_canonical_across_identical_books() {
        let first = KernelBook::new_at("BNT/USD", 10);
        let second = KernelBook::new_at("BNT/USD", 10);
        first
            .submit_limit(1, 100, 2, Side::Buy, TimeInForce::Gtc)
            .unwrap();
        second
            .submit_limit(1, 100, 2, Side::Buy, TimeInForce::Gtc)
            .unwrap();
        assert_eq!(
            first.snapshot_package(10).unwrap().checksum,
            second.snapshot_package(10).unwrap().checksum
        );
    }

    #[test]
    fn kill_switch_rejects_new_flow_but_allows_cancel() {
        let book = KernelBook::new("BNT/USD");
        book.submit_limit(1, 100, 10, Side::Buy, TimeInForce::Gtc)
            .unwrap();
        book.engage_kill_switch();

        assert!(matches!(
            book.submit_limit(2, 99, 1, Side::Buy, TimeInForce::Gtc),
            Err(OrderBookError::KillSwitchActive)
        ));
        assert!(book.cancel(1).unwrap());
    }

    #[test]
    fn checked_conversions_reject_invalid_values() {
        assert_eq!(
            to_upstream_order_id(OrderId::new(u128::from(u64::MAX) + 1)),
            Err(ConversionError::OrderIdOutOfRange)
        );
        assert_eq!(
            to_upstream_price(PriceTicks(0)),
            Err(ConversionError::InvalidPrice)
        );
        assert_eq!(
            to_upstream_quantity(QuantityLots(-1)),
            Err(ConversionError::InvalidQuantity)
        );
        assert_eq!(to_upstream_side(BuntingSide::Sell), Side::Sell);
    }
}
