#![forbid(unsafe_code)]
#![allow(clippy::missing_errors_doc)]
//! Bunting's thin, version-pinned adapter around `OrderBook-rs`.
//!
//! Matching, price levels, order types, trade generation, snapshots, replay helpers,
//! depth analytics, risk hooks, self-trade prevention, fees and the operational kill
//! switch are upstream responsibilities. Bunting owns authentication, canonical event
//! envelopes, participant accounting, persistence and Worker protocols.

use orderbook_rs::orderbook::OrderBookSnapshotPackage;
use orderbook_rs::{DefaultOrderBook, Id, OrderBookError, Side, TimeInForce, TradeResult};

pub use orderbook_rs::orderbook::ORDERBOOK_SNAPSHOT_FORMAT_VERSION;
pub use orderbook_rs::{
    EnrichedSnapshot, FeeSchedule, MetricFlags, OrderBookSnapshot, RejectReason, RiskConfig,
    STPMode, StubClock, TradeInfo,
};

/// Released upstream version approved for the Bunting kernel.
pub const ORDERBOOK_RS_VERSION: &str = "0.10.3";
/// Audited upstream source revision corresponding to the adopted implementation pass.
pub const ORDERBOOK_RS_AUDIT_COMMIT: &str = "575de34260b0fce346372074b6b938df058693a8";

/// Result of one limit-order submission through the upstream engine.
#[derive(Debug)]
pub struct LimitSubmission {
    /// Stable textual form of the upstream order identifier.
    pub order_id: String,
    /// Fills generated by this submission, when it crossed resting liquidity.
    pub trade_result: Option<TradeResult>,
}

/// The production book wrapper used by Bunting.
///
/// This type intentionally does not expose a second Bunting-owned matching structure.
pub struct KernelBook {
    inner: DefaultOrderBook,
}

impl KernelBook {
    /// Creates a book backed by `OrderBook-rs`.
    #[must_use]
    pub fn new(symbol: &str) -> Self {
        Self {
            inner: DefaultOrderBook::new(symbol),
        }
    }

    /// Exposes the upstream API for capabilities Bunting has not wrapped yet.
    #[must_use]
    pub const fn inner(&self) -> &DefaultOrderBook {
        &self.inner
    }

    /// Submits a limit order and returns only fills attributable to this call.
    pub fn submit_limit(
        &self,
        order_id: u64,
        price: u128,
        quantity: u64,
        side: Side,
        time_in_force: TimeInForce,
    ) -> Result<LimitSubmission, OrderBookError> {
        let (order, trade_result) = self.inner.add_limit_order_with_result(
            Id::from_u64(order_id),
            price,
            quantity,
            side,
            time_in_force,
            None,
        )?;

        Ok(LimitSubmission {
            order_id: order.id().to_string(),
            trade_result,
        })
    }

    /// Submits a market order and normalizes the upstream match result into a trade result.
    pub fn submit_market(
        &self,
        order_id: u64,
        quantity: u64,
        side: Side,
    ) -> Result<TradeResult, OrderBookError> {
        let match_result =
            self.inner
                .submit_market_order(Id::from_u64(order_id), quantity, side)?;
        Ok(TradeResult::new(
            self.inner.symbol().to_string(),
            match_result,
        ))
    }

    /// Cancels an order through the upstream order-location index.
    pub fn cancel(&self, order_id: u64) -> Result<bool, OrderBookError> {
        Ok(self
            .inner
            .cancel_order(Id::from_u64(order_id))?
            .is_some())
    }

    /// Engages the upstream operational kill switch.
    pub fn engage_kill_switch(&self) {
        self.inner.engage_kill_switch();
    }

    /// Releases the upstream operational kill switch.
    pub fn release_kill_switch(&self) {
        self.inner.release_kill_switch();
    }

    /// Creates the checksum-protected upstream snapshot package as JSON.
    pub fn snapshot_json(&self, depth: usize) -> Result<String, OrderBookError> {
        self.inner.create_snapshot_package(depth)?.to_json()
    }

    /// Restores a fresh upstream book from a validated snapshot package.
    pub fn restore_snapshot_json(symbol: &str, json: &str) -> Result<Self, OrderBookError> {
        let package = OrderBookSnapshotPackage::from_json(json)?;
        package.validate()?;
        let mut inner = DefaultOrderBook::new(symbol);
        inner.restore_from_snapshot_package(package)?;
        Ok(Self { inner })
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use super::*;

    #[test]
    fn limit_market_and_snapshot_restore_use_upstream_engine() {
        let book = KernelBook::new("BNT/USD");
        book.submit_limit(1, 100, 10, Side::Buy, TimeInForce::Gtc)
            .unwrap();
        book.submit_limit(2, 102, 8, Side::Sell, TimeInForce::Gtc)
            .unwrap();

        let before = book.snapshot_json(10).unwrap();
        let restored = KernelBook::restore_snapshot_json("BNT/USD", &before).unwrap();
        assert_eq!(book.inner().best_bid(), restored.inner().best_bid());
        assert_eq!(book.inner().best_ask(), restored.inner().best_ask());

        let result = book.submit_market(3, 3, Side::Buy).unwrap();
        assert_eq!(
            result
                .match_result
                .executed_quantity()
                .map_or(0, |quantity| quantity.as_u64()),
            3
        );
    }

    #[test]
    fn kill_switch_rejects_new_flow_but_allows_cancel() {
        let book = KernelBook::new("BNT/USD");
        book.submit_limit(1, 100, 10, Side::Buy, TimeInForce::Gtc)
            .unwrap();
        book.engage_kill_switch();

        assert!(matches!(
            book.submit_limit(2, 99, 1, Side::Buy, TimeInForce::Gtc),
            Err(OrderBookError::KillSwitchActive)
        ));
        assert!(book.cancel(1).unwrap());
    }
}
