#!/usr/bin/env python3
"""Generate the competitor protocol reference from the FIX Orchestra source."""

from pathlib import Path
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "schemas/fix/bunting.fixlatest.competition.v1.orchestra.xml"
OUTPUT = ROOT / "PROTOCOL.md"
NS = {"fixr": "http://fixprotocol.io/2020/orchestra/repository"}

repository = ET.parse(SOURCE).getroot()
fields = repository.findall("fixr:fields/fixr:field", NS)
messages = repository.findall("fixr:messages/fixr:message", NS)

lines = [
    "# Bunting competition FIX protocol",
    "",
    "<!-- Generated by tools/generate_protocol.py. Edit the Orchestra XML, not this file. -->",
    "",
    "The venue speaks FIXT.1.1 with FIX 5.0 SP2 application semantics and the "
    "`bunting.fixlatest.competition.v1` overlay. Logon must send tags 1137=9, "
    "10000=bunting.fixlatest.competition.v1, and the roster-assigned role in 10004.",
    "",
    "## Extension messages",
    "",
    "| MsgType | Name | Category |",
    "| --- | --- | --- |",
]
for message in messages:
    lines.append(
        f"| `{message.attrib['msgType']}` | {message.attrib['name']} | "
        f"{message.attrib['category']} |"
    )
lines.extend(
    [
        "",
        "## Extension fields",
        "",
        "| Tag | Name | Type |",
        "| ---: | --- | --- |",
    ]
)
for field in fields:
    lines.append(
        f"| {field.attrib['id']} | `{field.attrib['name']}` | "
        f"{field.attrib['type']} |"
    )
lines.extend(
    [
        "",
        "Standard order entry uses NewOrderSingle (`D`), OrderCancelRequest (`F`), "
        "ExecutionReport (`8`), MarketDataRequest (`V`), and "
        "MarketDataSnapshotFullRefresh (`W`). BuntingPayloadJSON (10020) contains "
        "bounded UTF-8 JSON for competition resources; it never changes FIX "
        "session sequencing or the authoritative event schema.",
        "",
        "The venue keeps the existing Bunting codec while the QuickFIX-Go "
        "interoperability gate remains green. Unknown tags and malformed frames "
        "are rejected within the published wire and rate limits.",
        "",
    ]
)
OUTPUT.write_text("\n".join(lines), encoding="utf-8")
